### PR TITLE
Tiny fixes

### PR DESCRIPTION
**Pull request by jiripospisil**
Hello, just a few things I noticed while setting up things locally. More details in the individual commits.

### CODE REVIEW

**Comment by sphaerophoria** [comment]
Thanks for the fixes. Looking into the 0 ball length thing, it looks like it is arguably a client side issue

If I log where the crash happens
```
diff --git a/src/res/wasm.js b/src/res/wasm.js
index 9c46011..76cc988 100644
--- a/src/res/wasm.js
+++ b/src/res/wasm.js
@@ -36,8 +36,9 @@ class SimulationCallbacks {
     return true;
   }

   stepChamber(balls_ptr, byte_len, num_balls, delta) {
+    console.log(balls_ptr, byte_len, num_balls)
     let sim_balls = new Uint8Array(
       this.simulation.instance.exports.memory.buffer,
       balls_ptr,
       byte_len,

```

We see `-1431655766 0 0`. If we check what value that is
```
>>> hex((1<<32) -1431655766)
'0xaaaaaaaa'
```
Ok, so we're getting the zig sentinel value for unassigned memory, likely from the Ball list getting freed. We then try to use that memory address which isn't valid and the client gets mad. I've committed a fix for that and credited you for finding the issue

**Comment by sphaerophoria** [comment]
Could you go into more detail on the blender symptoms? I'd like to see if I can understand the underlying issue a little more before taking the fix. Maybe like blender version, os, and error messages?

**Comment by jiripospisil** [comment]
It's on Arch Linux 6.9.9-arch1-1 with Blender 4.2.0.

```
rm -rf .zig-cache && zig build --verbose

cd /home/user/projects/ball-machine/src/chambers/dude && blender -b -P export_animation.py -- /home/user/projects/ball-machine/.zig-cache/o/3237a623f5dcd680f7f55d5bc6d6bebc/animation.zig 
install
└─ install dude
   └─ zig build-exe dude Debug wasm32-freestanding
      └─ run blender (animation.zig) stderr
OSError: Python file "/home/user/projects/ball-machine/export_animation.py" could not be opened: No such file or directory
```

It's doing the right thing! And indeed if I take the printed command and run it manually, it works fine and animation.zig has the correct content. It's just that for some reason Blender is still looking for the file in the current directory.

```
cd /home/user/projects/ball-machine/src/chambers/dude && blender -b -P export_animation.py -- /home/user/projects/ball-machine/.zig-cache/o/3237a623f5dcd680f7f55d5bc6d6bebc/animation.zig

Blender 4.2.0 (hash a51f293548ad built 2024-07-17 07:40:23)
Read blend: "/home/user/projects/ball-machine/src/chambers/dude/dude.blend"
/home/user/projects/ball-machine/.zig-cache/o/3237a623f5dcd680f7f55d5bc6d6bebc/animation.zig

Blender quit
```

With the workaround, the command looks like this and it works:

```
blender -b -P /home/user/projects/ball-machine/src/chambers/dude/export_animation.py -- /home/user/projects/ball-machine/.zig-cache/o/c849904ef14acfd492125c57e8f7301a/animation.zig
```

You're on NixOS, right? It looks like 4.2.0 is pretty new and you're most likely still on 4.1.1 but I don't know how they would achieve something like this even if they wanted to, so maybe the issue is somewhere else.

**Comment by jiripospisil** [comment]
Getting the same error even with 4.1.1.

**Comment by sphaerophoria** [comment]
That's so strange. Are you using zig 0.13.0? Installed from the repos? I'll make an arch vm and try to repro cause I really want to understand the difference

**Comment by sphaerophoria** [comment]
Ah perfect, I've managed to reproduce in a docker image, poking around to try to understand better

**Comment by sphaerophoria** [comment]
This also reproduces the same issue. 
```
const std = @import("std");

pub fn main() !void {
    const argv: []const []const u8 = &.{
        "blender",
        "-b",
        "-P",
        "export_animation.py",
        "--",
        "out.zig",
    };

    var gpa = std.heap.GeneralPurposeAllocator(.{}){};

    const alloc = gpa.allocator();

    var child = std.process.Child.init(argv, alloc);
    child.cwd = "src/chambers/dude";
    try child.spawn();
    _ = try child.wait();
}
```

**Comment by sphaerophoria** [comment]
Okay stracing the failing command above with 
`strace -f -e trace=execve -v  ./test2`

```
[pid  5007] execve("/usr/sbin/blender", ["blender", "-b", "-P", "export_animation.py", "--", "out.zig"], ["HOSTNAME=0ffc4239b7ba", "PWD=/root/ball-machine", "HOME=/root", "LANG=C.UTF-8", "TERM=xterm", "SHLVL=1", "PATH=/usr/local/sbin:/usr/local/"..., "OLDPWD=/root", "_=/usr/sbin/strace"]) = 0
```
PWD looks pretty sketch. What if we just do this directly in C?
```
#include <unistd.h>
int main(void) {
        chdir("src/chambers/dude");
        char* const args[] = {"blender", "-b", "-P", "export_animation.py", "--", "out.zig", NULL};
        char* const envp[] = {"PWD=/root/ball-machine", NULL};
        execve("/usr/sbin/blender", args, envp);
}
```
Okay in that C file if we pass envp = NULL it works as expected, but adding PWD= breaks it. I guess blender is getting the directory in some way that uses PWD. Why don't  I see this usually?

Well when I check strace of my build, I do see the same PWD issue, but running the same test.c above with the blender path swapped out does **NOT** cause problems. However on nixos blender is wrapping .blender_wrapped, and calling .blender_wrapped directly **DOES** cause problems.

Looking at the blender wrapper script, it isn't doing anything crazy
```
#! /nix/store/306znyj77fv49kwnkpxmb0j2znqpa8bj-bash-5.2p26/bin/bash -e
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/43jrkd6225zhmj48ik4lpcfd7k5yzjxr-python3.11-openusd-24.03/bin'':'/':'}
PATH='/nix/store/43jrkd6225zhmj48ik4lpcfd7k5yzjxr-python3.11-openusd-24.03/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/jrr6l56xssk4szz6xxk9mxhk8pxwghhg-python3.11-charset-normalizer-3.3.2/bin'':'/':'}
PATH='/nix/store/jrr6l56xssk4szz6xxk9mxhk8pxwghhg-python3.11-charset-normalizer-3.3.2/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/ylvsb39l0wq5q6xdphrq35an6dxqhjw9-python3.11-numpy-1.26.4/bin'':'/':'}
PATH='/nix/store/ylvsb39l0wq5q6xdphrq35an6dxqhjw9-python3.11-numpy-1.26.4/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/bin'':'/':'}
PATH='/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/a46b5cds6hhb8dycyf2s4bf4mcmgwcci-python3.11-defusedxml-0.7.1/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/a46b5cds6hhb8dycyf2s4bf4mcmgwcci-python3.11-defusedxml-0.7.1/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/760x7xf14jjvgmhzjb48g0y09k3iy5xf-python3.11-olefile-0.47/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/760x7xf14jjvgmhzjb48g0y09k3iy5xf-python3.11-olefile-0.47/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/bnkg9gk85zn8q37phhiiacrr407lqp7k-python3.11-pillow-10.3.0/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/bnkg9gk85zn8q37phhiiacrr407lqp7k-python3.11-pillow-10.3.0/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/q89kvx2abmj0vwlg06xbb9nlj6zakw2j-python3.11-pyopengl-3.1.7/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/q89kvx2abmj0vwlg06xbb9nlj6zakw2j-python3.11-pyopengl-3.1.7/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/scaky5i3jjcfmk23s6pgfd7z9izh0ajf-python3.11-markupsafe-2.1.5/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/scaky5i3jjcfmk23s6pgfd7z9izh0ajf-python3.11-markupsafe-2.1.5/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/cyhnqww4v87ms623dz12aadwi4jwbylj-python3.11-jinja2-3.1.4/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/cyhnqww4v87ms623dz12aadwi4jwbylj-python3.11-jinja2-3.1.4/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/43jrkd6225zhmj48ik4lpcfd7k5yzjxr-python3.11-openusd-24.03/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/43jrkd6225zhmj48ik4lpcfd7k5yzjxr-python3.11-openusd-24.03/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/462fi500v0yppj7fz5f46dpqg99i3g3z-python3.11-zstandard-0.22.0/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/462fi500v0yppj7fz5f46dpqg99i3g3z-python3.11-zstandard-0.22.0/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/2sd6mncv58k6065w8cf9b5pmagf2jc2f-python3.11-urllib3-2.2.1/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/2sd6mncv58k6065w8cf9b5pmagf2jc2f-python3.11-urllib3-2.2.1/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/y84qvvzrarmks4k7qb9ras6qfsxksnds-python3.11-idna-3.7/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/y84qvvzrarmks4k7qb9ras6qfsxksnds-python3.11-idna-3.7/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/jrr6l56xssk4szz6xxk9mxhk8pxwghhg-python3.11-charset-normalizer-3.3.2/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/jrr6l56xssk4szz6xxk9mxhk8pxwghhg-python3.11-charset-normalizer-3.3.2/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/qgglxpjjja3qpxi6mayabj417n16d3lh-python3.11-certifi-2024.02.02/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/qgglxpjjja3qpxi6mayabj417n16d3lh-python3.11-certifi-2024.02.02/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/i65kg4y70qxgw8sb1s35yg1sssc6qxa4-python3.11-pycparser-2.22/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/i65kg4y70qxgw8sb1s35yg1sssc6qxa4-python3.11-pycparser-2.22/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/n4dzhaf8ybxmmk4v47mx00mlllrmg0f0-python3.11-cffi-1.16.0/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/n4dzhaf8ybxmmk4v47mx00mlllrmg0f0-python3.11-cffi-1.16.0/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/cf9j4x1ka7s6aajgswvw23d36q4d2a2y-python3.11-brotlicffi-1.1.0.0/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/cf9j4x1ka7s6aajgswvw23d36q4d2a2y-python3.11-brotlicffi-1.1.0.0/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/nicjg1xpimrn3zfbndwix25gphv88zlx-python3.11-requests-2.31.0/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/nicjg1xpimrn3zfbndwix25gphv88zlx-python3.11-requests-2.31.0/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/ylvsb39l0wq5q6xdphrq35an6dxqhjw9-python3.11-numpy-1.26.4/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/ylvsb39l0wq5q6xdphrq35an6dxqhjw9-python3.11-numpy-1.26.4/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/4zhaq3y4djabrlvnzy9z8n2ik7jcnavc-python3.11-materialx-1.38.10/lib/python3.11/site-packages'':'/':'}
PYTHONPATH='/nix/store/4zhaq3y4djabrlvnzy9z8n2ik7jcnavc-python3.11-materialx-1.38.10/lib/python3.11/site-packages'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
exec -a "$0" "/nix/store/gwvf9l53wp8d0hifh7i2lyp62dp8ji2y-blender-4.1.1/bin/.blender-wrapped"  --python-use-system-env "$@" 
```

And if I make a lil' test.sh
```
#!/usr/bin/env bash
exec -a "$0" "/nix/store/gwvf9l53wp8d0hifh7i2lyp62dp8ji2y-blender-4.1.1/bin/.blender-wrapped"  --python-use-system-env "$@"
```

and adjust our script to use it
```
#include <stdio.h>
#include <unistd.h>
#include <errno.h>

int main(void) {
        if (chdir("src/chambers/dude") != 0) {
                printf("Invalid chdir\n");
        }
        char* const args[] = {"blender", "-b", "-P", "export_animation.py", "--", "out.zig", NULL};
        char* const envp[] = {"PWD=/root/ball-machine", NULL};
        printf("Launching\n");
        execve("/home/mick/work/ball-machine/test.sh", args, envp);
        printf("uh oh %d %d\n", errno, EFAULT);
}
```

It is also fine...

HOWEVER, if we echo $PWD in the test.sh script, we see that it has changed to src/chambers/dude, despite the set PWD in the envp.

Okay I think I'm happy enough with this explanation
* Blender prefers PWD over getcwd()
* Zig is passing the wrong PWD along with the build script, it's probably inheriting it from the parent. I've confirmed that building in my arch docker image from src/chambers/dude does pass the correct PWD
* Nix hides this because bash sets PWD to getcwd() in it's wrapper script

What a fun bug!

I'm hesitant to take the getPath() fix, because the zig docs say that this is meant to be used in the make phase, which we are not in. Technically it's fine, but there could be breakage later. I think a better fix is to just nuke the PWD env

It doesn't seem that easy to replace the existing env, but we can just set the env map and delete PWD manually

**Comment by sphaerophoria** [comment]
Blender source code triggering the issue
https://github.com/blender/blender/blob/604dc2cc33d00ef4ed8425260d97d1b08f7c8362/source/blender/blenlib/intern/storage.cc#L96

**Comment by sphaerophoria** [comment]
Alright, I think this can be closed. I took the typo fix in 1ae6a93a03ce57ae079a3edea427982a32299586, made an alternative fix to the 0 balls issue in 27134fe105eaaa427b2168f211d2e1912e767f4b, and made an alternative fix to the absolute path change in 8e961086d5819e3fed7570f6835fb08b01d2bb9c

Thanks for the PR!

**Comment by jiripospisil** [comment]
Nice investigation!

**Pull request closed without merging**
